### PR TITLE
Update workshop program. Minor 2020 -> 2022 changes.

### PR DESCRIPTION
**Pull request by mr-devs**
Most of these updates were to the workshop program outline based on what we have so far. However, there are some other small changes that update things to reference 2022 instead of 2020.

Please review for weird formatting issues. Loading on my end locally seems to look okay.

If everything looks okay, please merge it into the main branch so it goes to the live site.

### CODE REVIEW

**Comment by Ravi2712** [comment]
@mr-devs There are some places where it still shows 2020. Glance it over and comment which ones you think needs to be changed. I would be happy to change it!

- [ ] Registration deadlines
- [ ] Important Note (CDC Guideline)

**Comment by mr-devs** [comment]
> @mr-devs There are some places where it still shows 2020. Glance it over and comment which ones you think needs to be changed. I would be happy to change it!

Thanks, @Ravi2712 ! Good catches, for sure. Please do make any of these changes that you can! However, please merge the current changes (if they look okay) and then open other issues for these changes that we can address in different PRs.

**Comment by Ravi2712** [comment]
@mr-devs Do you think it would be good to have this PR as our giant PR for all 2020 -> 2022 changes? We can keep adding sub-tasks for only 2020 to 2022 changes in here.

**Comment by Ravi2712** [comment]
I think, it's not a good idea. I would agree with you because we can not see in live-version. Let's merge! 💯

**Comment by mr-devs** [comment]
Thanks for merging.

Just to be clear on my thoughts on the below.

> @mr-devs Do you think it would be good to have this PR as our giant PR for all 2020 -> 2022 changes? We can keep adding sub-tasks for only 2020 to 2022 changes in here.

Typically, I like to adopt the practice of small, incremental PR's. That way it's easier to understand the changes being made (not to mention faster to review!) and if we need to revert something that doesn't work well on the live site we can do so without messing up lots of other things.

**Pull request merged**
